
controller_manager:
  ros__parameters:
    use_sim_time: True
    update_rate: 500  # Hz

    joint_states_controller:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_group_effort_controller:
      type: effort_controllers/JointGroupEffortController

joint_group_effort_controller:
  ros__parameters:
    use_sim_time: True
    joints:
        - "comar/abad_1_joint"
        - "comar/hip_1_joint"
        - "comar/knee_1_joint"

        - "comar/abad_2_joint"
        - "comar/hip_2_joint"
        - "comar/knee_2_joint"

        - "comar/abad_3_joint"
        - "comar/hip_3_joint"
        - "comar/knee_3_joint"

        - "comar/abad_4_joint"
        - "comar/hip_4_joint"
        - "comar/knee_4_joint"


    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity


    gains:
      comar/abad_1_joint : {p: 180.0, d: 0.9, i: 20.0}
      comar/hip_1_joint  : {p: 180.0, d: 0.9, i: 20.0}
      comar/knee_1_joint : {p: 180.0, d: 0.9, i: 20.0}
      comar/abad_2_joint : {p: 180.0, d: 0.9, i: 20.0}
      comar/hip_2_joint  : {p: 180.0, d: 0.9, i: 20.0}
      comar/knee_2_joint : {p: 180.0, d: 0.9, i: 20.0}
      comar/abad_3_joint : {p: 180.0, d: 0.9, i: 20.0}
      comar/hip_3_joint  : {p: 180.0, d: 0.9, i: 20.0}
      comar/knee_3_joint : {p: 180.0, d: 0.9, i: 20.0}
      comar/abad_4_joint : {p: 180.0, d: 0.9, i: 20.0}
      comar/hip_4_joint  : {p: 180.0, d: 0.9, i: 20.0}
      comar/knee_4_joint : {p: 180.0, d: 0.9, i: 20.0}


